// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        print("windows");
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBuccJGFrI-RGM1cLo13VoeSpdNnfIxTvA",
    authDomain: "cmsc190-b3208.firebaseapp.com",
    projectId: "cmsc190-b3208",
    storageBucket: "cmsc190-b3208.appspot.com",
    messagingSenderId: "868745840330",
    appId: "1:868745840330:web:a18a3186ebf83c8bea5633",
    measurementId: "G-QSKTMHEW5F",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBuccJGFrI-RGM1cLo13VoeSpdNnfIxTvA",
    appId: "1:868745840330:android:b4cfc81f2858eefeea5633",
    messagingSenderId: "868745840330",
    projectId: "cmsc190-b3208",
    storageBucket: "cmsc190-b3208.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuccJGFrI-RGM1cLo13VoeSpdNnfIxTvA',
    appId: '1:868745840330:ios:2bacf2d53b0678dfea5633',
    messagingSenderId: '868745840330',
    projectId: 'cmsc190-b3208',
    storageBucket: 'cmsc190-b3208.appspot.com',
    // iosClientId:
    //     '788030627658-vd38op57vb52nq9kn3sbkj39mg6v32ve.apps.googleusercontent.com',
    // iosBundleId: 'com.example.exercise6',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDJ7UsgiuFhGny9kTD7xBkAHbYqtLWGRhU',
  //   appId: '1:788030627658:ios:26ef98f8207a11225aebb3',
  //   messagingSenderId: '788030627658',
  //   projectId: 'cmsc-23-project',
  //   storageBucket: 'cmsc-23-project.appspot.com',
  //   iosClientId:
  //       '788030627658-vd38op57vb52nq9kn3sbkj39mg6v32ve.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.exercise6',
  // );
}
