//In Used in All Widget
List<String> phase = [
  'Emergency Room',
  'In-Hospital',
  'Pending Surgery',
  'Pending Discharge',
  'Deceased',
];

//General
List<String> gender = [
  'Male',
  'Female',
  'Nonbinary',
];

//PreHospital
List<String> chiefComplaints = [
  'Unknown',
  'Trauma/Injuries',
  'Abdominal Pain',
  'Chest Pain',
  'Shortness of Breath',
  'Fever',
  'Headache',
  'Back Pain',
  'Weakness/Fatigue',
  'Dizziness/Vertigo',
  'Nausea/Vomiting',
  'Rash/Skin Problems',
  'Urinary Symptoms',
  'Joint Pain/Swelling',
  'Numbness/Tingling',
  'Seizures',
  'Cough',
  'Sore Throat',
  'Difficulty Swallowing',
  'Bleeding/Clotting',
  'Fatigue',
  'Swelling in Limbs',
  'Changes in Vision',
  'Difficulty Speaking',
  'Confusion/Memory Loss',
  'Sleep Disturbances',
  'Weight Changes',
  'Chest Tightness',
  'Palpitations',
  'Muscle Cramps',
  'Irregular Menstrual Cycle',
  'Abnormal Bleeding',
  'Swollen Lymph Nodes',
  'Difficulty Walking',
  'Balance Problems',
  'Loss of Appetite',
  'Heartburn/Indigestion',
  'Abnormal Bowel Movements',
  'Constipation',
  'Diarrhea',
  'Rectal Bleeding',
  'Heart Palpitations',
  'Sudden Weight Loss',
  'Blood in Urine/Stool',
  'Frequent Infections',
  'Feeling Cold/Hot',
  'Excessive Thirst',
  'Excessive Sweating',
  'Chest Pressure',
  'Jaw Pain',
  'Neck Pain',
  'Shoulder Pain',
  'Arm Pain',
  'Leg Pain',
  'Foot Pain',
  'Hand Pain',
  'Hip Pain',
  'Pelvic Pain',
  'Groin Pain',
  'Ear Pain',
  'Eye Pain',
  'Mouth Pain',
  'Tooth Pain',
  'Jaw Clicking/Popping',
  'Swollen Joints',
  'Skin Lesions/Wounds',
  'Chest Wall Deformities',
  'Abdominal Distention',
  'Jaundice',
  'Difficulty Breathing When Lying Down',
  'Wheezing',
  'Changes in Bowel Habits',
  'Loss of Smell/Taste',
  'Excessive Gas',
  'Fainting/Loss of Consciousness',
  'Skin Discoloration',
  'Hair Loss',
  'Bruising Easily',
  'Memory Problems',
  'Muscle Weakness',
  'Abnormal Gait',
  'Vertigo on Movement',
  'Difficulty Concentrating',
  'Unusual Body Odor',
  'Impaired Balance/Coordination',
  'Abnormal Posture',
  'Difficulty Chewing',
  'Hoarseness',
  'Changes in Skin Texture',
  'Swollen Glands',
];

List<String> placesOfOccurrence = [
  'Home',
  'Workplace',
  'Road/Highway',
  'School/College/University',
  'Park/Recreation Area',
  'Sports Ground/Stadium',
  'Shopping Mall/Market',
  'Restaurant/Cafeteria',
  'Public Transportation',
  'Airport/Airfield',
  'Beach/Pool',
  'Construction Site',
  'Industrial Area/Factory',
  'Farm/Agricultural Field',
  'Gym/Fitness Center',
  'Theater/Cinema',
  'Concert Venue',
  'Event/Festival',
  'Street/Sidewalk',
  'Parking Lot/Garage',
  'Unknown',
  '',
];

List<String> otherRisksFactors = [
  'Alcohol consumption',
  'Drug use',
  'Fatigue',
  'Medical condition (e.g., seizure, heart attack)',
  'Distracted driving (e.g., texting, eating)',
  'Speeding',
  'Inexperience',
  'Emotional distress',
  'Physical impairment',
  'Mental impairment'
];

List<String> naturesOfInjury = [
  //require
  'None',
  'Others',
  //Fractures
  'Fracture (Closed Type)',
  'Fracture (Open Type)',
  //Soft tissue injuries
  'Contusions',
  'Lacerations',
  'Abrasions',
  'Bruising',
  //Burns
  'First-degree burns',
  'Second-degree burns',
  'Third-degree burns',
  //Traumatic injuries
  'Concussions',
  'Traumatic brain injuries',
  'Internal organ injuries',
  'Hemorrhages',
  //Specific to external causes
  'Bite wounds',
  'Scratches',
  'Stab wounds',
  'Gunshot wounds',
  'Cutting wounds',
  'Drowning-related injuries',
  'Smoke inhalation injuries',
  'Carbon monoxide poisoning',
  'Electric shock injuries',
  'Fall-related injuries',
  'Crush injuries',
  'Suffocation-related injuries',
  'Explosion-related injuries',
  'Fire-related injuries',
  'Chemical burns',
  'Smoke inhalation injuries',
];

List<String> externalCausesInjury = [
  //require
  'None',
  //Animals
  'Bites',
  'Animal attacks',
  //Humans
  'Physical Assault',
  'Stabbing',
  'Gunshot',
  'Self-harm',
  //Activities
  'Drowning',
  'Firecrackers',
  'Vehicle accidents',
  'Sports-related injuries',
  'Occupational hazards',
  'Substance Abuse',
  'Chemical exposures',
  //Others
  'Electrocution',
  'Explosions',
  'Falls from heights',
  'Suffocation',
  'Fires',
  'Natural Calamity',
];

List<String> safetyIssues = [
  'Sleepy',
  'Alcohol',
  'Drugs',
  'Smoking',
  'Seatbelt',
  'Airbag',
  'Helmet',
  'Life Jacket'
];
List<String> modeOfTranspo = [
  'Private Vehicle',
  'Police Vehicle',
  'Ambulance',
  'Public Transportation',
];
List<String> cavitiesForSurgery = [
  'Head',
  'Neck',
  'Chest',
  'Abdomen',
  'Extremity',
  'Superficial'
];
List<String> servicesOnboard = [
  'General Surgery',
  'Ortho',
  'OB',
  'Neurosurgery',
  'Plastics',
  'TCVS',
  'Optha',
  'ENT'
];
List<String> disposition = [
  'Admit (Surgery)',
  'Admit (In-Hospital)',
  'Treated and for Discharge',
  'No intervention and for Discharge',
  'HAMA/Refused Admission',
  'Absconded',
  'Died',
  'Transferred'
];
List<String> injuryTypeList = [
  'Unintentional',
  'Intentional',
  'Self-inflicted',
  'Undetermined'
];
List<String> medicolegalList = [
  "Women's deaths/injuries",
  "Self-harm/suicide",
  "Child abuse/neglect",
  "Poisoning",
  "Sharp object/firearm injuries",
  "Drowning",
  "Road/industrial accidents",
  "Conditions requiring legal notification",
  "Suspected foul play",
  "Uncertain cause of death",
  "Sexual assault",
  "Domestic violence",
  "Work-related injuries/deaths",
  "Medical malpractice",
  "Human trafficking",
  "Homicide",
  "Drug overdoses",
  "Unexplained sudden deaths",
];
List<String> positionOfPatientList = [
  'Driver',
  'Passenger',
  'Captain',
  'Pilot',
  'Crew Member',
  'Pedestrian',
];
List<String> vehiclesList = [
  'Car',
  "Van",
  "Bus",
  "Motorcycle",
  "Bicycle",
  "Tricycle",
  "Jeepney",
  "Truck",
  "Boat",
  "Plane"
];
List<String> vehicleAccidentType = ['Land', 'Air', 'Sea'];
List<String> yesNoList = ['yes', 'no'];
List<String> firstAidMethods = [
  'CPR (Cardiopulmonary Resuscitation)',
  'Heimlich Maneuver',
  'Applying Pressure to Stop Bleeding',
  'Treating Burns',
  'Treating Fractures',
  'Managing Shock',
  'Treating Heat Exhaustion or Heatstroke',
  'Treating Hypothermia',
  'Bandaging Wounds',
  'Administering Epinephrine for Severe Allergic Reactions',
];

//ER

//In Hospital
List<String> vteTypes = [
  'Splanchnic Vein Thrombosis',
  'Pelvic Vein Thrombosis',
  'Ovarian Vein Thrombosis',
  'Uterine Vein Thrombosis',
  'Vena Caval Thrombosis',
  'Cerebral Deep Vein Thrombosis',
  'Retinal Vein Thrombosis',
  'Sinus Vein Thrombosis',
  'Brachiocephalic Vein Thrombosis',
  'Renal Artery Thrombosis',
  'Hepatic Artery Thrombosis',
  'Splenic Artery Thrombosis',
  'Mesenteric Artery Thrombosis',
  'Subclavian Artery Thrombosis',
  'Axillary Artery Thrombosis',
  'Carotid Artery Thrombosis',
  'Coronary Artery Thrombosis',
  'Superior Mesenteric Vein Thrombosis',
  'Inferior Mesenteric Vein Thrombosis',
  'Azygos Vein Thrombosis',
  'Hemiazygos Vein Thrombosis',
  'Accessory Hemiazygos Vein Thrombosis',
  'Vertebral Vein Thrombosis',
];

List<String> consultationServices = [
  'Cardiology',
  'Dermatology',
  'Endocrinology',
  'Gastroenterology',
  'Hematology',
  'Neurology',
  'Oncology',
  'Orthopedics',
  'Pediatrics',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Urology',
  'Allergy and Immunology',
  'Anesthesiology',
  'Cardiothoracic Surgery',
  'Critical Care Medicine',
  'Emergency Medicine',
  'Family Medicine',
  'Geriatric Medicine',
  'Infectious Disease',
  'Internal Medicine',
  'Nephrology',
  'Ophthalmology',
  'Otolaryngology (ENT)',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Podiatry',
  'Sports Medicine',
];

//Surgery
List<String> surgeryDispositions = [
  'Satisfactory Recovery',
  'Delayed Recovery',
  'Complications',
  'Partial Success',
  'No Improvement',
  'Worsening of Condition',
  'Recovery with Disabilities',
  'Palliative Care',
  'Reoperation',
  'Long-Term Management',
];

List<String> surgeryTypes = [
  "Laparotomy", // Often used for abdominal trauma
  "Amputation", // Common in severe limb trauma
  "Craniotomy", // Used in traumatic brain injury
  "Thoracotomy", // Used for chest trauma
  "Splenectomy", // Often required after trauma to the spleen
  "Tracheostomy", // May be required in severe facial/airway trauma
  "Arthroscopy", // Joint injuries
  "Laminectomy", // Spinal trauma
  "Nephrectomy", // Kidney removal due to trauma
  "Hemicolectomy", // Partial removal of colon after trauma
  "Esophagectomy", // Trauma-related esophageal damage
  "Rhinoplasty", // Facial/nasal trauma
  "Debridement", // Removal of damaged tissue or foreign objects in trauma
  "Fasciotomy", // Relieves pressure in cases of compartment syndrome, often after severe injury
  "External Fixation", // Stabilization of fractured bones after trauma
  "Internal Fixation", // Pins, plates, rods for fractures after trauma
  "Skin Grafting", // Common after burns or severe lacerations
  "Orthopedic Reduction", // Realignment of fractures or dislocations
  "Tendon Repair", // After laceration or rupture from trauma
  "Facial Reconstruction", // Severe facial injuries
  "Vascular Repair", // Trauma involving blood vessels
  "Pelvic Fixation", // Stabilizing pelvic fractures
  "Reimplantation Surgery", // Reattaching severed limbs or digits
  "Maxillofacial Surgery", // Complex facial fractures or trauma
  "Exploratory Surgery", // For diagnosing hidden trauma in soft tissues
  "Chest Tube Insertion", // Managing traumatic pneumothorax or hemothorax
];

List<String> hemorrhageControlTypes = [
  "Direct pressure",
  "Tourniquet",
  "Hemostatic dressing",
  "Compression bandage",
  "Suturing",
  "Vascular clamp",
  "Hemostatic agent",
  "Cauterization",
  "Embolization",
  "Hemostatic forceps",
  "Ligation",
  "Hemostatic powder",
  "Controlled hypotension",
  "Hemorrhage control medication",
  "Blood transfusion",
  "Fluid resuscitation",
  "Angiography",
  "Endovascular intervention",
  "Surgical intervention",
  "Radiation therapy",
  "Chemotherapy",
  "Targeted therapy",
  "Immunotherapy",
  "Stem cell transplant",
  "Bone marrow transplant",
  "Peripheral blood stem cell transplant",
  "Hematopoietic cell transplant",
  "Autologous transplant",
  "Allogeneic transplant",
  "Syngeneic transplant",
  "Blood products",
  "Platelets",
  "Red blood cells",
  "Plasma",
  "Cryoprecipitate",
  "Factor concentrates",
  "Antifibrinolytic agents",
  "Procoagulant agents",
  "Fibrin sealants",
  "Artificial blood",
  "Blood substitutes",
];

//Surgery
List<String> comorbiditiesList = [
  'Hypertension',
  'Diabetes Mellitus',
  //'Cardiovascular Disease',
  'Coronary Artery Disease (CAD)',
  'Hypertensive Heart Disease',
  'Congestive Heart Failure (CHF)',
  'Myocardial Infarction (Heart Attack)',
  'Arrhythmias',
  'Valvular Heart Disease',
  'Cardiomyopathy',
  'Peripheral Artery Disease (PAD)',
  'Aortic Aneurysm',
  'Pulmonary Embolism',
  'Rheumatic Heart Disease',
  'Endocarditis',
  'Heart Valve Disorders',
  'Congenital Heart Defects',
  //'Chronic Obstructive Pulmonary Disease (COPD)',
  'Chronic Bronchitis',
  'Emphysema',
  'Chronic Asthma',
  'Bronchiectasis',
  //'Chronic Kidney Disease',
  'Glomerulonephritis',
  'Diabetic Nephropathy',
  'Hypertensive Nephrosclerosis',
  'Polycystic Kidney Disease (PKD)',
  'Tubulointerstitial Nephritis',
  'Kidney Stones (Nephrolithiasis)',
  'Renal Artery Stenosis',
  'Lupus Nephritis',
  'Alport Syndrome',
  'Fabry Disease',
  //'Liver Disease',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'Hepatitis D',
  'Hepatitis E',
  'Cirrhosis',
  'Nonalcoholic Fatty Liver Disease (NAFLD)',
  'Alcoholic Liver Disease',
  'Liver Cancer (Hepatocellular Carcinoma)',
  'Autoimmune Hepatitis',
  'Primary Biliary Cholangitis (PBC)',
  'Primary Sclerosing Cholangitis (PSC)',
  'Wilson\'s Disease',
  'Hemochromatosis',
  'Cancer',
  'Depression or Other Mental Health Disorders',
  'Rheumatologic Conditions',
  'Neurological Disorders',
  'Gastrointestinal Disorders',
  'Obesity',
  'Asthma',
  'Immunocompromised Conditions',
  'Thyroid Disorders',
  'Sleep Apnea',
  'Osteoporosis',
  'Autoimmune Diseases',
  'HIV/AIDS',
  'Stroke History',
  'Peripheral Vascular Disease',
  'Eating Disorders',
  'Substance Abuse Disorders',
];

List<String> complicationsList = [
  'Common cold',
  'Influenza',
  'Pneumonia',
  'Cystitis',
  'Pyelonephritis',
  'Gastroenteritis',
  'Food poisoning',
  'Cellulitis',
  'Abscess',
  'Chlamydia',
  'Gonorrhea',
  'Syphilis',
  'Sepsis',
  'Bacteremia',
  'Wound infections',
  'Deep tissue infections',
  'Meningitis',
  'Encephalitis',
  'Osteomyelitis',
  'Septic arthritis',
  'Conjunctivitis',
  'Keratitis',
  'Otitis media',
  'Otitis externa',
  'Candidiasis',
  'Aspergillosis',
  'Malaria',
  'Giardiasis',
  'HIV/AIDS',
  'Hepatitis',
  'Rabies',
  'Lyme disease',
  'Hospital-acquired pneumonia',
  'Surgical site infections',
  'Malaria',
  'Dengue fever',
  'Malaria',
  'Zika virus',
  'Streptococcal throat infection',
  'Urinary tract infection',
  'Urinary Tract Infections (UTIs)',
  'Pressure Ulcers (Bedsores)',
  'Venous Thromboembolism (VTE)',
  'Delirium',
  'Falls and Fractures',
  'Medication Errors',
  'Acute Kidney Injury (AKI)',
  'Electrolyte Imbalances',
  'Respiratory Complications',
  'Cardiac Events',
  'Sepsis',
  'Gastrointestinal Bleeding',
  'Fluid and Electrolyte Imbalance',
  'Malnutrition',
  'Surgical Complications',
  'Acute Respiratory Distress Syndrome (ARDS)',
  'Disorientation and Confusion',
  'Venous Access Complications',
  'Hematologic Complications',
];
